/**
 * Alerts — Emergency advisories and warnings.
 */
import React from 'react';
import { useApi } from '../hooks/useApi';
import { api } from '../services/api';
import { Card, SectionLabel, LoadingState, ErrorState } from '../components/ui';
import type { EmergencyAlert } from '../types';

export const Alerts: React.FC = () => {
  const { data: alerts, loading, error, refetch } = useApi<EmergencyAlert[]>(api.getAllAlerts);

  if (loading) return <LoadingState count={4} />;
  if (error) return <ErrorState message={error} onRetry={refetch} />;
  if (!alerts) return null;

  return (
    <div className="animate-fade-up">
      <div className="view-head">
        <div>
          <h1>Emergency Alerts</h1>
          <p>Automated warnings generated by the risk prediction engine.</p>
        </div>
      </div>

      <SectionLabel icon="bell-ringing" title="Active Advisories" />
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-4)' }}>
        {alerts.map((alert: EmergencyAlert) => (
          <Card 
            key={alert.id} 
            style={{ 
              borderLeft: `4px solid ${alert.level.includes('critical') ? 'var(--alert)' : 'var(--warn)'}`,
              padding: '16px 20px'
            }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
              <div>
                <h3 style={{ fontSize: '15px', marginBottom: '8px' }}>{alert.title}</h3>
                <div style={{ display: 'flex', gap: '16px', fontSize: '12px', color: 'var(--text-dim)', flexWrap: 'wrap' }}>
                  <span>Districts: <strong style={{ color: 'var(--text)' }}>{alert.districts || alert.district}</strong></span>
                  <span>Affected Pop: <strong style={{ color: 'var(--text)', fontFamily: 'var(--font-mono)' }}>{alert.population}</strong></span>
                  <span>AI Confidence: <strong style={{ color: 'var(--text)', fontFamily: 'var(--font-mono)' }}>{alert.confidence}%</strong></span>
                </div>
              </div>
              <div style={{ background: 'var(--alert-dim)', color: 'var(--alert)', padding: '6px 12px', borderRadius: 'var(--r-sm)', fontFamily: 'var(--font-mono)', fontWeight: 600, fontSize: '13px' }}>
                Active
              </div>
            </div>
          </Card>
        ))}
        {alerts.length === 0 && (
          <div style={{ padding: 'var(--sp-8)', textAlign: 'center', color: 'var(--text-dim)' }}>
            No active emergency alerts at this time.
          </div>
        )}
      </div>
    </div>
  );
};
